apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcomic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcomic
  template:
    metadata:
      labels:
        app: testcomic
    spec:
      containers:
      - name: nginxcomic
        image: devops2022.azurecr.io/comicbook:4430e7e40c5e7253b3e3c7452b94550e9edc2bc3 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testcomic-service
spec:
  selector:
    app: testcomic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comicingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts: 
      - devopsdaemons.devops2022.de
      secretName: fakecertificate-tls
  rules:
  - host: devopsdaemons.devops2022.de
    http:
      paths:
      - path: /.*
        pathType: Prefix
        backend:
          service:
            name: testcomic-service
            port:
              number: 80

              
