apiVersion: app/v1
kind: Deployment
metadata:
  name: knote
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: devops2022.azurecr.io/devops-daemons-argocd:79a3bb6d0883222db3e0396508b3cb12c901c7e1 
          ports:
            - containerPort: 3000
          imagePullPolicy: Always