apiVersion: app/v1
kind: Deployment
metadata:
  name: knote
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: devops2022.azurecr.io/devops-daemons-argocd:76bb488623c5c6c4c49809984d7803613579cb42 
          ports:
            - containerPort: 3000
          imagePullPolicy: Always