apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allinone.yml
  - nginx_config_map.yml
  - service_monitor.yml
images:
   - name: nginxcomic
     newName: devops2022.azurecr.io/comicbook
     newTag: 301c1763e42f2f2ab9100ad7c08fd4b90cf62dcb
