apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - ingress.yml
images:
  - name: nodejs
    newName: devops2022.azurecr.io/repo-demo-marc
    newTag: 9f4a54e9a848846f49d48257642b5af7b8880e70
