apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - ingress.yml
images:
  - name: nodejs
    newName: devops2022.azurecr.io/devops-daemons-argocd
    newTag: 79a3bb6d0883222db3e0396508b3cb12c901c7e1
