apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - ingress.yml
images:
  - name: nodejs
    newName: devops2022.azurecr.io/team-3-argotest
    newTag: 38c567a7f3c20738930d61cd93792a2f8c79897e
