apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen    80;
      server_name devopsdaemons.devops2022.de;

      location / {
          root /usr/share/nginx/html;
          index.html index.htm;
      }

      location / nginx_status {
          stub_status;
          allow 20.23.166.37; 
          deny all; 
      }

      error_page 500 502 503 504 /50x.html;
      location = /50x.html{
        root /usr/share/nginx/html;
      }
    }