- name: Playbook
  gather_facts: no
  hosts: VM
  become: yes
  tasks:
    - name: Copy file
      copy: 
        content: |
        Testlauf Marc.
        {{ somedict }}
      dest: home/jester/testfile.txt 
    tags:
      - content     