apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dropdrop
  name: deployment
  labels: 
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: devops2022.azurecr.io/nginx:latest
        ports:
        - containerPort: 80