apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dropdrop
  name: deployment
  labels: 
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: devops2022.azurecr.io/dropdrop:$GIT_COMMIT
        ports:
        - containerPort: 80
        resources:
            limits:
              cpu: 100m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata: 
  name: service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer