apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
images:
  - name: MAK-NGINX
    newName: devops2022.azurecr.io/marc:7d266a671acab6b1542d7502a638ac2a90a7a5ee
