apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
images:
  - name: MAK-NGINX
    newName: devops2022.azurecr.io/marc:8fd24dfe137544267e70f00dddc53f0adf0063f2
