apiVersion: kustomize.config.k8s.io/v1beta1
                        kind: Kustomization
                        resources:
                            - deployment.yml
                        images:
                            - name: nginx
                        newName: devops2022.azurecr.io/dropdrop:cad8677a0f6935f5c22a680b9c7df3c952aa979f
