- name: Playbook
  hosts: VM
  tasks:
    - name: install dependencies
      anible-builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: true  
      check_mode: true  
    - name: add docker apt key
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg  
        state: "present"
      check_mode: true  
    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      check_mode: true  
    - name: install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true
      check_mode: true