- name: Playbook
  hosts: VM
  tasks:
    - name: install dependencies
      anible-builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: true  
    - name: add docker apt key
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg  
        state: "present"
      