apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team3-ingress
spec:
  rules:
  - host: devops2022.de
    http:
      paths:
      - path: /team3
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              name: http
