apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: felixstrauss
spec:
  selector:
    app: nginx
  ports:
   - name: https
#   - protocol: TCP
     port: 443
     targetPort: 80
  type: ClusterIP  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules: 
  - host: devops2022.de
    http: 
      paths:
      - path: /felixstrauss
        pathType: Prefix
        backend:
            service:
              name: nginx-service
              port: 
                name: https
#                number: 80
