apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: felixstrauss
spec:
  selector:
    app: nginx
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
  type: LoadBalancer
